sudo: required
dist: precise
language: cpp

matrix:
  include:

    # 1/ Linux Clang Builds
   - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

    # 2/ Linux GCC Builds
  - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    # 3/ OSX Clang Builds
    - os: osx
      osx_image: xcode10.1
    
    - os: osx
      osx_image: xcode9.4
      
before_install:
    - eval "${MATRIX_EVAL}"
    
addons:
  apt:
    packages:
      - cmake
      - libboost-dev
      - libboost-test-dev
      - lcov    

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - cmake -H. -Bbin -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - cd bin

script:
  - make -j 2
  - ctest -V -j 2

