version: 0.0.1.{build}

configuration:
- Debug
- Release

environment:
  matrix:
  - VS_VERSION: 14
    VS_PLATFORM: win32
  - VS_VERSION: 14
    VS_PLATFORM: x64

before_build:
- git submodule update --init --recursive
- cmake -H. -Bbin/VS -G "Visual Studio %VS_VERSION%" -DCMAKE_GENERATOR_PLATFORM=%VS_PLATFORM% -DBUILD_SHARED_LIBS=true -Wno-dev

build:
  project: bin\VS\ara.sln
  parallel: true
  verbosity: minimal

test_script:
- cd bin\VS && if %CONFIGURATION%==Debug (ctest --verbose -E perftest --build-config %CONFIGURATION%) else (ctest --verbose --build-config %CONFIGURATION%)
