version: 1.0.{build}
image: Visual Studio 2022

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    GENERATOR: Visual Studio 17 2022
    CONFIG: Release
    ARCH_ARG: -A x64
    
build_script:
- cmd: >-
    cmake -G "%GENERATOR%" -H. -B_builds -DENABLE_TESTING=1
    cmake --build _builds --config "%CONFIG%"
    
test_script:
- cmd: >-
    cd _builds
    ctest -VV -C "%CONFIG%"